export const dummyAlerts = [
  {
    alert_id: 901,
    user_id: 3,
    username: 'a.reed',
    access_log_id: 2881,
    alert_type: 'HONEYTOKEN_ACCESS',
    severity: 'CRITICAL',
    message: 'Honeytoken credentials opened from unmanaged endpoint',
    status: 'OPEN',
    created_at: '2026-04-20T10:28:00Z',
  },
  {
    alert_id: 902,
    user_id: 7,
    username: 'c.chen',
    access_log_id: 2883,
    alert_type: 'HONEYTOKEN_ACCESS',
    severity: 'HIGH',
    message: 'Decoy payroll export triggered from unusual subnet',
    status: 'OPEN',
    created_at: '2026-04-20T12:02:00Z',
  },
  {
    alert_id: 903,
    user_id: 4,
    username: 's.king',
    access_log_id: 2888,
    alert_type: 'RISK_SPIKE',
    severity: 'MEDIUM',
    message: 'Rapid lateral movements exceeded policy threshold',
    status: 'ACKNOWLEDGED',
    created_at: '2026-04-20T14:41:00Z',
  },
];

export const dummyLogs = [
  {
    log_id: 2881,
    user_id: 3,
    username: 'a.reed',
    resource_id: 55,
    resource_name: 'Finance_Archive_2026.zip',
    token_id: 1007,
    access_type: 'READ',
    ip_address: '10.20.44.92',
    is_honeytoken: 1,
    access_time: '2026-04-20T10:26:04Z',
  },
  {
    log_id: 2882,
    user_id: 9,
    username: 'j.patel',
    resource_id: 70,
    resource_name: 'engineering-oncall.md',
    token_id: null,
    access_type: 'READ',
    ip_address: '10.20.43.77',
    is_honeytoken: 0,
    access_time: '2026-04-20T10:41:55Z',
  },
  {
    log_id: 2883,
    user_id: 7,
    username: 'c.chen',
    resource_id: 59,
    resource_name: 'Payroll_Admin_Portal.txt',
    token_id: 1012,
    access_type: 'EXPORT',
    ip_address: '172.18.12.8',
    is_honeytoken: 1,
    access_time: '2026-04-20T12:00:12Z',
  },
  {
    log_id: 2884,
    user_id: 5,
    username: 'l.baker',
    resource_id: 84,
    resource_name: 'incident-template.docx',
    token_id: null,
    access_type: 'WRITE',
    ip_address: '10.20.41.39',
    is_honeytoken: 0,
    access_time: '2026-04-20T12:11:01Z',
  },
  {
    log_id: 2888,
    user_id: 4,
    username: 's.king',
    resource_id: 77,
    resource_name: 'Prod_DB_KeyVault.json',
    token_id: 1004,
    access_type: 'READ',
    ip_address: '192.168.2.44',
    is_honeytoken: 1,
    access_time: '2026-04-20T14:39:33Z',
  },
];

export const dummyRiskUsers = {
  3: {
    user: {
      user_id: 3,
      username: 'a.reed',
      risk_score: 64,
      role_id: 2,
      department_id: 1,
      is_active: true,
    },
    risk_history: [
      {
        risk_event_id: 30,
        old_score: 34,
        points_added: 30,
        new_score: 64,
        reason: 'Honeytoken access detected for resource_id=55, token_id=1007',
        event_time: '2026-04-20T10:26:04Z',
      },
      {
        risk_event_id: 22,
        old_score: 16,
        points_added: 18,
        new_score: 34,
        reason: 'Policy threshold exceeded in off-hours sequence',
        event_time: '2026-04-18T03:17:10Z',
      },
    ],
  },
  7: {
    user: {
      user_id: 7,
      username: 'c.chen',
      risk_score: 49,
      role_id: 3,
      department_id: 2,
      is_active: true,
    },
    risk_history: [
      {
        risk_event_id: 31,
        old_score: 25,
        points_added: 24,
        new_score: 49,
        reason: 'Honeytoken access detected for resource_id=59, token_id=1012',
        event_time: '2026-04-20T12:00:12Z',
      },
    ],
  },
};
